import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/nav";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { StyledEngineProvider } from "@mui/material";
import Footer from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} id="root">
        <AppRouterCacheProvider>
          <StyledEngineProvider injectFirst>
            <div className="main" />
            <main className="app">
              <Nav />
              {children}
            </main>
            <Footer />
          </StyledEngineProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
